### ISSUE TITLE
Default to installing the latest

### ISSUE THREAD

**Issue by mscoutermarsh** [planetscale/heroku-buildpack-planetscale#1]
Once https://github.com/planetscale/cli/issues/279 is figured out, we can update the buildpack to always pull the latest version.

**Comment by mscoutermarsh** [comment]
Or (after reading the comment) realized we could use the script @fatih used: https://github.com/planetscale/cli/issues/279#issuecomment-852011077

If github api is down for some reason we should prob have a fallback to a hardcoded version.

**Comment by no-itsbackpack** [comment]
thanks for the comment from fatih, we can use the same script and fallback to the hardcoded version in the code
